#!/usr/bin/env node

const {parserSync} = require('shargs')
const {command, flag} = require('shargs-opts')

const opts   = [
  flag('help', ['--help'])
]

const git    = command('git', opts)

const parser = parserSync()
const parse  = parser(git)

const argv   = process.argv.slice(2)
const res    = parse(argv)

console.log(JSON.stringify(res, null, 2))