#!/usr/bin/env node

const {parserSync} = require('shargs')
const {command} = require('shargs-opts')

const git    = command('git', [])

const parser = parserSync()
const parse  = parser(git)

const argv   = process.argv.slice(2)
const res    = parse(argv)

console.log(JSON.stringify(res, null, 2))